//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB7
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public int MaSo { get; set; }
        public string MaMH { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual Mon Mon { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
